-- Seed data for DS Gap Insights.
--
-- This project no longer ships demo submissions. The submissions table should
-- contain real user-submitted gaps only.
--
-- Running this file is intentionally a no-op.
