import { Sparkles } from "lucide-react";

export function AiBadge({
  mode,
}: {
  mode: "fixtures" | "live";
}) {
  return (
    <span
      className="inline-flex items-center gap-1 rounded-full border border-border bg-card px-2 py-0.5 text-[11px] font-medium uppercase tracking-wide text-muted-foreground"
      title={
        mode === "live"
          ? "Generated by a live LLM call"
          : "Generated by deterministic fixtures (no LLM call)"
      }
    >
      <Sparkles className="size-3" aria-hidden />
      AI {mode === "live" ? "live" : "fixture"}
    </span>
  );
}
