// Seed list of known DS components. Edit this list to match your
// actual design system. Designers may type free text — anything not in
// this list will be saved as-is but flagged in the submission row.
export const KNOWN_COMPONENTS = [
  "Actions",
  "Accordion Tab",
  "Accordion",
  "Auto Complete",
  "Avatar Group",
  "Avatar",
  "Blanket",
  "Breadcrumb",
  "Button",
  "Card",
  "Category Chip",
  "Checkbox",
  "Chip - With Avatar",
  "Chip Group",
  "Chips",
  "Color Picker",
  "Confirm Modal",
  "Date Picker",
  "Divider",
  "Dropdown",
  "File Upload",
  "Fit Score",
  "Grid",
  "Helper",
  "Icon",
  "Icon Button",
  "Input Chip",
  "Input Field",
  "Input Number",
  "Label",
  "Link Text",
  "List Items",
  "Listbox",
  "Menu Item",
  "Menu",
  "Modal",
  "Multi Select",
  "Notification Badge",
  "Number Badge",
  "Pagination",
  "Popover",
  "Progress Bar",
  "Progress Spinner",
  "Radio Button",
  "Radio Group",
  "Radio Panels",
  "Rating",
  "Rich Text Editor",
  "Scroll",
  "Search",
  "Search With Category",
  "Sidebar Navigation",
  "Sidebar",
  "Slider",
  "Snackbar",
  "Skeleton",
  "Split Button",
  "Status",
  "Switch",
  "Switch Button",
  "System Message",
  "Tab",
  "Table",
  "Tag",
  "Talent Signal",
  "Text Area",
  "Text Button",
  "Tiered Menu",
  "Tooltip",
  "Tristate Checkbox",
  "View Selector",
  "Wizard Stepper",
] as const;

export type KnownComponent = (typeof KNOWN_COMPONENTS)[number];
