// Seed list of known DS components. Edit this list to match your
// actual design system. Designers may type free text — anything not in
// this list will be saved as-is but flagged in the submission row.
export const KNOWN_COMPONENTS = [
  "Button",
  "Icon Button",
  "Split Button",
  "Switch Button",
  "Text Button",
  "Paginator",
  "Table",
  "Scroller",
  "Autocomplete",
  "Input Text",
  "Label",
  "Calendar",
  "Checkbox",
  "Chip Group",
  "Dropdown",
  "Helper",
  "Input Number",
  "Link Text",
  "Multi Select",
  "Radio Button",
  "Radio Group",
  "Rating",
  "Search Input",
  "Search With Category",
  "Slider",
  "Input Switch",
  "Textarea",
  "Text Editor",
  "Tristate Checkbox",
  "Accordion Tab",
  "Accordion",
  "Card",
  "Divider",
  "Blanket",
  "Confirm Dialog",
  "Dialog",
  "Popover",
  "Sidebar",
  "Tooltip",
  "Snackbar",
  "System Messages",
  "Sidebar Navigation",
  "Breadcrumb",
  "Category Chip",
  "Menu",
  "Tab",
  "Tiered Menu",
  "View Selector",
  "Wizard Stepper",
] as const;

export type KnownComponent = (typeof KNOWN_COMPONENTS)[number];
